// ─── SUPPORTED LANGUAGES ─────────────────────────────────────────────────────
// Only languages with 100% key coverage are listed here.
// Adding a language here without all keys will cause missing text.
export const LANGS = {
  en:{f:"🇬🇧",n:"English",na:"English"},
  de:{f:"🇩🇪",n:"German",na:"Deutsch"},
  fr:{f:"🇫🇷",n:"French",na:"Français"},
  es:{f:"🇪🇸",n:"Spanish",na:"Español"},
  it:{f:"🇮🇹",n:"Italian",na:"Italiano"},
  pl:{f:"🇵🇱",n:"Polish",na:"Polski"},
  sr:{f:"🇷🇸",n:"Serbian",na:"Srpski"},
  hr:{f:"🇭🇷",n:"Croatian",na:"Hrvatski"},
  mk:{f:"🇲🇰",n:"Macedonian",na:"Македонски"},
  tr:{f:"🇹🇷",n:"Turkish",na:"Türkçe"},
};

// ─── MASTER KEY LIST — every t() call in the app ─────────────────────────────
// If you add a new t('key') call, add it to EVERY language below.
const KEYS = [
  'detecting','langDetected','continueIn','chooseOther','chooseLanguage',
  'allowLocation','locationDesc','allow','skipNow','gettingLoc','locPrivacy',
  'home','fixNow','nearby','parts','emergency',
  'goodMorning','goodAfternoon','goodEvening','welcome','descProblem',
  'emergencyHelp','emergencySubtitle',
  'whatNeedsFixing','homeRepair','carProblems','techDevices','garden','appliances','petHealth','tapToFix',
  'enableLocBanner','enableLocDesc',
  'fixItNow','descOrPhoto','takePhoto','photoDesc','cameraUpload',
  'describeWords','getAIGuide','commonProblems',
  'diagnosing','diagnosingWait','aiUnavailable','aiUnavailableDesc',
  'aiNoKey','aiNoKeyDesc','tryAgain',
  'diagnosis','possibleCauses','safetyWarning',
  'stepByStep','step','of',
  'toolsNeeded','partsNeeded','expertTip',
  'proRequired','findProNearMe','findParts','findPro','back','photoTip',
  'emergencyMode','whatsHappening','selectCategory',
  'callNow','tapToCall','immediateSteps','openMapNear',
  'emergencyPlumber','plumberQuery',
  'nearestGarage','emergencyVet','electricityProvider','emergencyNumbers',
  'animalClinicNear',
  'findNearby','refresh','loadingPlaces',
  'noResults','noResultsDesc','openGoogleMaps','realResultsFrom',
  'locationNeeded','locationNeededDesc','enableLocation',
  'couldNotLoad','couldNotLoadDesc',
  'call','website','openNow','allResultsMap',
  'catGarage','catParts','catTyres','catPetrol','catHardware','catVet','catIT',
  'partsFinder','partsSubtitle','searchingFor',
  'catCar','catHome','catAppliance','catGarden','catTech','catBike','catPets',
  'vehicleInputCar','vehicleInputBike','vehicleInputHome','vehicleInputDefault','vehicleHint',
  'whatPartNeeded','partInputPlaceholder','findPartsBtn','typePartFirst',
  'localStores','onlineStores','findNearYou','gpsUsed','enableGPS',
  'storesFor','resultsFor','vehicle','hsnDetected','hsnDesc',
];

// ─── TRANSLATIONS ─────────────────────────────────────────────────────────────
const T = {};

T.en = {
  detecting:"Detecting language…", langDetected:"Language detected!",
  continueIn:"Continue in", chooseOther:"Choose a different language", chooseLanguage:"Choose Language",
  allowLocation:"Allow Location Access",
  locationDesc:"FixIt uses your location to find nearby repair shops, parts stores, and emergency services.",
  allow:"Allow Location", skipNow:"Skip for now", gettingLoc:"Getting your location…",
  locPrivacy:"Your location is only used to find nearby services. Never stored or shared.",
  home:"Home", fixNow:"Fix Now", nearby:"Nearby", parts:"Parts", emergency:"Emergency",
  goodMorning:"Good morning,", goodAfternoon:"Good afternoon,", goodEvening:"Good evening,",
  welcome:"Welcome to FixIt 👋", descProblem:"Describe your problem…",
  emergencyHelp:"⚡ Emergency Help", emergencySubtitle:"Burst pipe · Gas · Car breakdown · Pet emergency",
  whatNeedsFixing:"What needs fixing?",
  homeRepair:"Home Repair", carProblems:"Car Problems", techDevices:"Tech & Devices",
  garden:"Garden", appliances:"Appliances", petHealth:"Pet Health", tapToFix:"Tap to fix →",
  enableLocBanner:"Enable location for real nearby results",
  enableLocDesc:"Find real mechanics, stores and emergency services near you",
  fixItNow:"Fix It Now 🔧", descOrPhoto:"Describe or photograph your problem",
  takePhoto:"Take a Photo or Upload", photoDesc:"AI reads your photo and diagnoses the exact problem",
  cameraUpload:"📷 Camera / Upload", describeWords:"Or describe in words",
  getAIGuide:"🤖 Get AI Repair Guide", commonProblems:"Common Problems",
  diagnosing:"Analysing your problem…", diagnosingWait:"This takes about 10 seconds",
  aiUnavailable:"AI Analysis Temporarily Unavailable",
  aiUnavailableDesc:"Our AI is momentarily unavailable. Please try again in a moment.",
  aiNoKey:"AI guide not configured on this deployment.",
  aiNoKeyDesc:"Add VITE_ANTHROPIC_KEY in Vercel → Settings → Environment Variables, then redeploy.",
  tryAgain:"Try Again",
  diagnosis:"🔍 Diagnosis", possibleCauses:"Possible Causes", safetyWarning:"⚠️ Safety Warning",
  stepByStep:"📋 Step-by-Step Repair Guide", step:"Step", of:"of",
  toolsNeeded:"🔩 Tools Needed", partsNeeded:"📦 Parts Needed", expertTip:"⭐ Expert Tip",
  proRequired:"👨‍🔧 Professional Required", findProNearMe:"🗺️ Find Professional Near Me",
  findParts:"🔩 Find Parts", findPro:"👨‍🔧 Find Pro", back:"Back", photoTip:"💡 Pro tip",
  emergencyMode:"Emergency Mode", whatsHappening:"What's happening? 🚨",
  selectCategory:"Select a category for immediate help",
  callNow:"📞 Call Now", tapToCall:"Tap to call", immediateSteps:"📋 Immediate Steps",
  openMapNear:"Opens map near your location",
  emergencyPlumber:"Emergency Plumber 24h",
  plumberQuery:"emergency plumber water damage repair near me",
  nearestGarage:"Nearest Garage", emergencyVet:"Emergency Vet Now",
  electricityProvider:"Electricity Provider", emergencyNumbers:"Emergency Numbers",
  animalClinicNear:"Animal clinic / vet near me",
  findNearby:"🗺️ Find Nearby", refresh:"Refresh", loadingPlaces:"Loading nearby places…",
  noResults:"No results found nearby", noResultsDesc:"Try another category or open Google Maps",
  openGoogleMaps:"🗺️ Open in Google Maps", realResultsFrom:"real results from OpenStreetMap",
  locationNeeded:"Location needed", locationNeededDesc:"Enable GPS to find real businesses near you",
  enableLocation:"Enable Location", couldNotLoad:"Could not load places",
  couldNotLoadDesc:"Check your internet and try again",
  call:"Call", website:"Website", openNow:"Open now",
  allResultsMap:"See all results with reviews and directions",
  catGarage:"Garage", catParts:"Car Parts", catTyres:"Tyres",
  catPetrol:"Petrol", catHardware:"Hardware", catVet:"Vet", catIT:"IT Repair",
  partsFinder:"🔩 Parts Finder", partsSubtitle:"Find exact parts — smart local & online search",
  searchingFor:"What are you searching parts for?",
  catCar:"🚗 Car", catHome:"🏠 Home", catAppliance:"🍳 Appliance",
  catGarden:"🌿 Garden", catTech:"💻 Tech", catBike:"🚲 Bike", catPets:"🐾 Pet",
  vehicleInputCar:"e.g. 2019 VW Golf 1.6 TDI, VIN, or model name",
  vehicleInputBike:"e.g. Trek Marlin 5 2022 or brand/model",
  vehicleInputHome:"e.g. Samsung WW80T4040CE or model number",
  vehicleInputDefault:"e.g. brand, model, or part number",
  vehicleHint:"🇩🇪 HSN/TSN · 🇬🇧 Plate · 🇺🇸 VIN · or model name",
  whatPartNeeded:"What part do you need?",
  partInputPlaceholder:"e.g. brake pads, air filter, water pump, screen…",
  findPartsBtn:"🔍 Find Parts + Best Prices", typePartFirst:"Type a part name above to search",
  localStores:"📍 Local Stores", onlineStores:"🌍 Online Stores",
  findNearYou:"Find near you on Google Maps", gpsUsed:"Using your GPS location",
  enableGPS:"Enable GPS for better results", storesFor:"Stores for", resultsFor:"Results for",
  vehicle:"vehicle", hsnDetected:"HSN/TSN Detected",
  hsnDesc:"Opens Autodoc for 100% compatible parts for your exact vehicle.",
};

T.de = {
  detecting:"Sprache wird erkannt…", langDetected:"Sprache erkannt!",
  continueIn:"Weiter auf", chooseOther:"Andere Sprache wählen", chooseLanguage:"Sprache wählen",
  allowLocation:"Standort erlauben",
  locationDesc:"FixIt verwendet Ihren Standort, um Werkstätten, Ersatzteilhändler und Notfalldienste in Ihrer Nähe zu finden.",
  allow:"Standort erlauben", skipNow:"Überspringen", gettingLoc:"Standort wird ermittelt…",
  locPrivacy:"Ihr Standort wird nur zur Anzeige lokaler Dienste verwendet. Keine Speicherung.",
  home:"Startseite", fixNow:"Reparieren", nearby:"In der Nähe", parts:"Teile", emergency:"Notfall",
  goodMorning:"Guten Morgen,", goodAfternoon:"Guten Tag,", goodEvening:"Guten Abend,",
  welcome:"Willkommen bei FixIt 👋", descProblem:"Problem beschreiben…",
  emergencyHelp:"⚡ Notfallhilfe", emergencySubtitle:"Rohrbruch · Gas · Autopanne · Tiernotfall",
  whatNeedsFixing:"Was muss repariert werden?",
  homeRepair:"Hausreparatur", carProblems:"Autoprobleme", techDevices:"Technik & Geräte",
  garden:"Garten", appliances:"Haushaltsgeräte", petHealth:"Tiergesundheit",
  tapToFix:"Tippen zum Reparieren →",
  enableLocBanner:"Standort aktivieren für Ergebnisse in der Nähe",
  enableLocDesc:"Echte Werkstätten, Shops und Notfalldienste in Ihrer Nähe finden",
  fixItNow:"Jetzt reparieren 🔧", descOrPhoto:"Problem beschreiben oder fotografieren",
  takePhoto:"Foto aufnehmen oder hochladen",
  photoDesc:"Die KI liest Ihr Foto und stellt die genaue Diagnose",
  cameraUpload:"📷 Kamera / Hochladen", describeWords:"Oder in Worten beschreiben",
  getAIGuide:"🤖 KI-Reparaturanleitung erhalten", commonProblems:"Häufige Probleme",
  diagnosing:"Problem wird analysiert…", diagnosingWait:"Das dauert etwa 10 Sekunden",
  aiUnavailable:"KI-Analyse momentan nicht verfügbar",
  aiUnavailableDesc:"Unser KI-System ist vorübergehend nicht erreichbar. Bitte erneut versuchen.",
  aiNoKey:"KI-Reparaturanleitung nicht konfiguriert.",
  aiNoKeyDesc:"Fügen Sie VITE_ANTHROPIC_KEY in Vercel → Einstellungen → Umgebungsvariablen hinzu und starten Sie neu.",
  tryAgain:"Erneut versuchen",
  diagnosis:"🔍 Diagnose", possibleCauses:"Mögliche Ursachen", safetyWarning:"⚠️ Sicherheitshinweis",
  stepByStep:"📋 Schritt-für-Schritt-Anleitung", step:"Schritt", of:"von",
  toolsNeeded:"🔩 Benötigte Werkzeuge", partsNeeded:"📦 Benötigte Teile", expertTip:"⭐ Expertentipp",
  proRequired:"👨‍🔧 Fachkraft erforderlich", findProNearMe:"🗺️ Fachkraft in der Nähe finden",
  findParts:"🔩 Teile finden", findPro:"👨‍🔧 Fachkraft finden", back:"Zurück", photoTip:"💡 Profi-Tipp",
  emergencyMode:"Notfallmodus", whatsHappening:"Was ist passiert? 🚨",
  selectCategory:"Kategorie für sofortige Hilfe wählen",
  callNow:"📞 Jetzt anrufen", tapToCall:"Tippen zum Anrufen",
  immediateSteps:"📋 Sofortige Maßnahmen", openMapNear:"Öffnet Karte in Ihrer Nähe",
  emergencyPlumber:"Sanitär-Notdienst 24h",
  plumberQuery:"Sanitär Notdienst Rohrbruch Notdienst in der Nähe",
  nearestGarage:"Nächste Werkstatt", emergencyVet:"Notfalltierarzt jetzt",
  electricityProvider:"Stromnetzbetreiber", emergencyNumbers:"Notrufnummern",
  animalClinicNear:"Tierarzt / Tierklinik in der Nähe",
  findNearby:"🗺️ In der Nähe", refresh:"Aktualisieren",
  loadingPlaces:"Orte in der Nähe werden geladen…",
  noResults:"Keine Ergebnisse in der Nähe", noResultsDesc:"Andere Kategorie versuchen oder Google Maps öffnen",
  openGoogleMaps:"🗺️ In Google Maps öffnen", realResultsFrom:"echte Ergebnisse von OpenStreetMap",
  locationNeeded:"Standort erforderlich", locationNeededDesc:"GPS aktivieren um echte Betriebe in der Nähe zu finden",
  enableLocation:"Standort aktivieren", couldNotLoad:"Orte konnten nicht geladen werden",
  couldNotLoadDesc:"Internetverbindung prüfen und erneut versuchen",
  call:"Anrufen", website:"Website", openNow:"Jetzt geöffnet",
  allResultsMap:"Alle Ergebnisse mit Bewertungen und Navigation",
  catGarage:"Werkstatt", catParts:"Autoteile", catTyres:"Reifen",
  catPetrol:"Tankstelle", catHardware:"Baumarkt", catVet:"Tierarzt", catIT:"IT-Reparatur",
  partsFinder:"🔩 Teile-Finder", partsSubtitle:"Exakte Teile finden — intelligente lokale & Online-Suche",
  searchingFor:"Wofür suchen Sie Teile?",
  catCar:"🚗 Auto", catHome:"🏠 Zuhause", catAppliance:"🍳 Gerät",
  catGarden:"🌿 Garten", catTech:"💻 Technik", catBike:"🚲 Fahrrad", catPets:"🐾 Tier",
  vehicleInputCar:"z.B. 2019 VW Golf 1.6 TDI, HSN/TSN, FIN oder Modell",
  vehicleInputBike:"z.B. Trek Marlin 5 2022 oder Marke/Modell",
  vehicleInputHome:"z.B. Samsung WW80T4040CE oder Modellnummer",
  vehicleInputDefault:"z.B. Marke, Modell oder Teilenummer",
  vehicleHint:"🇩🇪 HSN/TSN · 🇬🇧 Kennzeichen · 🇺🇸 FIN · oder Modell",
  whatPartNeeded:"Welches Teil brauchen Sie?",
  partInputPlaceholder:"z.B. Bremsbeläge, Luftfilter, Wasserpumpe, Display…",
  findPartsBtn:"🔍 Teile + beste Preise finden", typePartFirst:"Teilename oben eingeben um zu suchen",
  localStores:"📍 Lokale Geschäfte", onlineStores:"🌍 Online-Shops",
  findNearYou:"In Ihrer Nähe auf Google Maps finden", gpsUsed:"Verwendet Ihren GPS-Standort",
  enableGPS:"GPS aktivieren für bessere Ergebnisse", storesFor:"Shops für", resultsFor:"Ergebnisse für",
  vehicle:"Fahrzeug", hsnDetected:"HSN/TSN Erkannt",
  hsnDesc:"Öffnet Autodoc.de für 100% kompatible Teile für Ihr genaues Fahrzeug.",
};

T.fr = {
  detecting:"Détection de la langue…", langDetected:"Langue détectée!",
  continueIn:"Continuer en", chooseOther:"Choisir une autre langue", chooseLanguage:"Choisir la langue",
  allowLocation:"Autoriser la localisation",
  locationDesc:"FixIt utilise votre position pour trouver des réparateurs, des pièces et des services d'urgence près de vous.",
  allow:"Autoriser", skipNow:"Ignorer", gettingLoc:"Localisation en cours…",
  locPrivacy:"Votre position n'est utilisée que pour les services à proximité. Jamais stockée.",
  home:"Accueil", fixNow:"Réparer", nearby:"À proximité", parts:"Pièces", emergency:"Urgence",
  goodMorning:"Bonjour,", goodAfternoon:"Bon après-midi,", goodEvening:"Bonsoir,",
  welcome:"Bienvenue sur FixIt 👋", descProblem:"Décrivez votre problème…",
  emergencyHelp:"⚡ Aide d'urgence", emergencySubtitle:"Fuite · Gaz · Panne · Urgence animale",
  whatNeedsFixing:"Qu'est-ce qui doit être réparé?",
  homeRepair:"Réparation maison", carProblems:"Problèmes de voiture", techDevices:"Tech & Appareils",
  garden:"Jardin", appliances:"Électroménager", petHealth:"Santé animale",
  tapToFix:"Appuyer pour réparer →",
  enableLocBanner:"Activez la localisation pour des résultats à proximité",
  enableLocDesc:"Trouvez de vrais ateliers, magasins et services d'urgence près de vous",
  fixItNow:"Réparer maintenant 🔧", descOrPhoto:"Décrivez ou photographiez votre problème",
  takePhoto:"Prendre une photo ou télécharger",
  photoDesc:"L'IA lit votre photo et diagnostique le problème exactement",
  cameraUpload:"📷 Appareil photo / Télécharger", describeWords:"Ou décrivez en mots",
  getAIGuide:"🤖 Obtenir le guide de réparation IA", commonProblems:"Problèmes courants",
  diagnosing:"Analyse du problème en cours…", diagnosingWait:"Environ 10 secondes…",
  aiUnavailable:"Analyse IA momentanément indisponible",
  aiUnavailableDesc:"Notre système IA est temporairement indisponible. Veuillez réessayer.",
  aiNoKey:"Guide IA non configuré sur ce déploiement.",
  aiNoKeyDesc:"Ajoutez VITE_ANTHROPIC_KEY dans Vercel → Paramètres → Variables d'environnement, puis redéployez.",
  tryAgain:"Réessayer",
  diagnosis:"🔍 Diagnostic", possibleCauses:"Causes possibles", safetyWarning:"⚠️ Avertissement de sécurité",
  stepByStep:"📋 Guide étape par étape", step:"Étape", of:"sur",
  toolsNeeded:"🔩 Outils nécessaires", partsNeeded:"📦 Pièces nécessaires", expertTip:"⭐ Conseil d'expert",
  proRequired:"👨‍🔧 Professionnel requis", findProNearMe:"🗺️ Trouver un pro près de moi",
  findParts:"🔩 Trouver des pièces", findPro:"👨‍🔧 Trouver un pro", back:"Retour", photoTip:"💡 Conseil pro",
  emergencyMode:"Mode urgence", whatsHappening:"Que se passe-t-il? 🚨",
  selectCategory:"Sélectionnez une catégorie pour une aide immédiate",
  callNow:"📞 Appeler maintenant", tapToCall:"Appuyer pour appeler",
  immediateSteps:"📋 Étapes immédiates", openMapNear:"Ouvre la carte à proximité",
  emergencyPlumber:"Dépannage plomberie 24h",
  plumberQuery:"plombier urgence dégât des eaux fuite près de moi",
  nearestGarage:"Garage le plus proche", emergencyVet:"Vétérinaire urgence",
  electricityProvider:"Fournisseur électricité", emergencyNumbers:"Numéros d'urgence",
  animalClinicNear:"Clinique vétérinaire à proximité",
  findNearby:"🗺️ À proximité", refresh:"Actualiser", loadingPlaces:"Chargement des lieux…",
  noResults:"Aucun résultat trouvé", noResultsDesc:"Essayez une autre catégorie ou ouvrez Google Maps",
  openGoogleMaps:"🗺️ Ouvrir dans Google Maps", realResultsFrom:"résultats réels d'OpenStreetMap",
  locationNeeded:"Localisation requise", locationNeededDesc:"Activez le GPS pour trouver des entreprises à proximité",
  enableLocation:"Activer la localisation", couldNotLoad:"Impossible de charger les lieux",
  couldNotLoadDesc:"Vérifiez votre connexion et réessayez",
  call:"Appeler", website:"Site web", openNow:"Ouvert maintenant",
  allResultsMap:"Tous les résultats avec avis et itinéraires",
  catGarage:"Garage", catParts:"Pièces auto", catTyres:"Pneus",
  catPetrol:"Carburant", catHardware:"Bricolage", catVet:"Vétérinaire", catIT:"Réparation IT",
  partsFinder:"🔩 Recherche de pièces", partsSubtitle:"Trouvez des pièces exactes — recherche locale et en ligne",
  searchingFor:"Pour quoi cherchez-vous des pièces?",
  catCar:"🚗 Voiture", catHome:"🏠 Maison", catAppliance:"🍳 Appareil",
  catGarden:"🌿 Jardin", catTech:"💻 Tech", catBike:"🚲 Vélo", catPets:"🐾 Animal",
  vehicleInputCar:"ex. Renault Clio 1.5 dCi 2019 ou modèle",
  vehicleInputBike:"ex. marque/modèle vélo", vehicleInputHome:"ex. numéro de modèle",
  vehicleInputDefault:"ex. marque, modèle ou référence",
  vehicleHint:"🇩🇪 HSN/TSN · 🇬🇧 Plaque · 🇺🇸 VIN · ou modèle",
  whatPartNeeded:"Quelle pièce cherchez-vous?",
  partInputPlaceholder:"ex. plaquettes de frein, filtre à air, pompe à eau…",
  findPartsBtn:"🔍 Trouver pièces + meilleurs prix", typePartFirst:"Saisissez un nom de pièce pour rechercher",
  localStores:"📍 Magasins locaux", onlineStores:"🌍 Boutiques en ligne",
  findNearYou:"Trouver près de vous sur Google Maps", gpsUsed:"Utilise votre position GPS",
  enableGPS:"Activez GPS pour de meilleurs résultats", storesFor:"Magasins pour", resultsFor:"Résultats pour",
  vehicle:"véhicule", hsnDetected:"HSN/TSN Détecté",
  hsnDesc:"Ouvre Autodoc pour des pièces 100% compatibles avec votre véhicule.",
};

T.es = {
  detecting:"Detectando idioma…", langDetected:"¡Idioma detectado!",
  continueIn:"Continuar en", chooseOther:"Elegir otro idioma", chooseLanguage:"Elegir idioma",
  allowLocation:"Permitir ubicación",
  locationDesc:"FixIt usa tu ubicación para encontrar talleres, repuestos y servicios de emergencia cercanos.",
  allow:"Permitir", skipNow:"Omitir", gettingLoc:"Obteniendo ubicación…",
  locPrivacy:"Tu ubicación solo se usa para encontrar servicios cercanos. Nunca se almacena.",
  home:"Inicio", fixNow:"Reparar", nearby:"Cerca", parts:"Repuestos", emergency:"Emergencia",
  goodMorning:"Buenos días,", goodAfternoon:"Buenas tardes,", goodEvening:"Buenas noches,",
  welcome:"Bienvenido a FixIt 👋", descProblem:"Describe tu problema…",
  emergencyHelp:"⚡ Ayuda de emergencia", emergencySubtitle:"Tubería · Gas · Avería · Emergencia animal",
  whatNeedsFixing:"¿Qué necesita repararse?",
  homeRepair:"Reparación del hogar", carProblems:"Problemas del coche", techDevices:"Tecnología y dispositivos",
  garden:"Jardín", appliances:"Electrodomésticos", petHealth:"Salud animal",
  tapToFix:"Toca para reparar →",
  enableLocBanner:"Activa ubicación para resultados cercanos",
  enableLocDesc:"Encuentra talleres reales, tiendas y servicios de emergencia cerca",
  fixItNow:"Reparar ahora 🔧", descOrPhoto:"Describe o fotografía tu problema",
  takePhoto:"Tomar foto o subir imagen", photoDesc:"La IA diagnostica el problema exacto desde tu foto",
  cameraUpload:"📷 Cámara / Subir", describeWords:"O describe en palabras",
  getAIGuide:"🤖 Guía de reparación IA", commonProblems:"Problemas comunes",
  diagnosing:"Analizando tu problema…", diagnosingWait:"Unos 10 segundos…",
  aiUnavailable:"Análisis IA momentáneamente no disponible",
  aiUnavailableDesc:"Nuestro sistema IA no está disponible temporalmente. Inténtalo de nuevo.",
  aiNoKey:"Guía IA no configurada en este despliegue.",
  aiNoKeyDesc:"Añade VITE_ANTHROPIC_KEY en Vercel → Configuración → Variables de entorno y vuelve a desplegar.",
  tryAgain:"Intentar de nuevo",
  diagnosis:"🔍 Diagnóstico", possibleCauses:"Posibles causas", safetyWarning:"⚠️ Advertencia de seguridad",
  stepByStep:"📋 Guía paso a paso", step:"Paso", of:"de",
  toolsNeeded:"🔩 Herramientas necesarias", partsNeeded:"📦 Repuestos necesarios", expertTip:"⭐ Consejo de experto",
  proRequired:"👨‍🔧 Profesional requerido", findProNearMe:"🗺️ Encontrar profesional cerca",
  findParts:"🔩 Encontrar repuestos", findPro:"👨‍🔧 Encontrar profesional", back:"Volver", photoTip:"💡 Consejo pro",
  emergencyMode:"Modo emergencia", whatsHappening:"¿Qué está pasando? 🚨",
  selectCategory:"Selecciona una categoría para ayuda inmediata",
  callNow:"📞 Llamar ahora", tapToCall:"Toca para llamar",
  immediateSteps:"📋 Pasos inmediatos", openMapNear:"Abre mapa cerca de ti",
  emergencyPlumber:"Servicio fontanería urgencias 24h",
  plumberQuery:"fontanero urgencias daños agua cerca de mí",
  nearestGarage:"Taller más cercano", emergencyVet:"Veterinario urgencias",
  electricityProvider:"Proveedor electricidad", emergencyNumbers:"Números de emergencia",
  animalClinicNear:"Clínica veterinaria cerca de mí",
  findNearby:"🗺️ Cerca", refresh:"Actualizar", loadingPlaces:"Cargando lugares…",
  noResults:"No se encontraron resultados", noResultsDesc:"Prueba otra categoría o abre Google Maps",
  openGoogleMaps:"🗺️ Abrir en Google Maps", realResultsFrom:"resultados reales de OpenStreetMap",
  locationNeeded:"Ubicación necesaria", locationNeededDesc:"Activa el GPS para encontrar negocios cercanos",
  enableLocation:"Activar ubicación", couldNotLoad:"No se pudieron cargar los lugares",
  couldNotLoadDesc:"Comprueba tu conexión e inténtalo de nuevo",
  call:"Llamar", website:"Sitio web", openNow:"Abierto ahora",
  allResultsMap:"Todos los resultados con reseñas y direcciones",
  catGarage:"Taller", catParts:"Repuestos auto", catTyres:"Neumáticos",
  catPetrol:"Gasolina", catHardware:"Ferretería", catVet:"Veterinario", catIT:"Reparación IT",
  partsFinder:"🔩 Buscador de repuestos", partsSubtitle:"Encuentra repuestos exactos — búsqueda local e inteligente",
  searchingFor:"¿Para qué buscas repuestos?",
  catCar:"🚗 Coche", catHome:"🏠 Casa", catAppliance:"🍳 Aparato",
  catGarden:"🌿 Jardín", catTech:"💻 Tech", catBike:"🚲 Bici", catPets:"🐾 Mascota",
  vehicleInputCar:"ej. Toyota Corolla 2019 o matrícula",
  vehicleInputBike:"ej. marca/modelo bicicleta", vehicleInputHome:"ej. número de modelo del aparato",
  vehicleInputDefault:"ej. marca, modelo o referencia",
  vehicleHint:"🇩🇪 HSN/TSN · 🇬🇧 Matrícula · 🇺🇸 VIN · o modelo",
  whatPartNeeded:"¿Qué pieza necesitas?",
  partInputPlaceholder:"ej. pastillas de freno, filtro de aire, bomba de agua…",
  findPartsBtn:"🔍 Encontrar repuestos + mejores precios", typePartFirst:"Escribe el nombre de la pieza para buscar",
  localStores:"📍 Tiendas locales", onlineStores:"🌍 Tiendas online",
  findNearYou:"Encontrar cerca de ti en Google Maps", gpsUsed:"Usando tu ubicación GPS",
  enableGPS:"Activa GPS para mejores resultados", storesFor:"Tiendas para", resultsFor:"Resultados para",
  vehicle:"vehículo", hsnDetected:"HSN/TSN Detectado",
  hsnDesc:"Abre Autodoc para piezas 100% compatibles con tu vehículo exacto.",
};

T.it = {
  detecting:"Rilevamento lingua…", langDetected:"Lingua rilevata!",
  continueIn:"Continua in", chooseOther:"Scegli un'altra lingua", chooseLanguage:"Scegli lingua",
  allowLocation:"Consenti posizione",
  locationDesc:"FixIt usa la tua posizione per trovare officine, ricambi e servizi di emergenza vicino a te.",
  allow:"Consenti", skipNow:"Salta", gettingLoc:"Localizzazione in corso…",
  locPrivacy:"La tua posizione è usata solo per i servizi locali. Mai memorizzata.",
  home:"Home", fixNow:"Ripara", nearby:"Vicino", parts:"Ricambi", emergency:"Emergenza",
  goodMorning:"Buongiorno,", goodAfternoon:"Buon pomeriggio,", goodEvening:"Buona sera,",
  welcome:"Benvenuto su FixIt 👋", descProblem:"Descrivi il problema…",
  emergencyHelp:"⚡ Aiuto emergenza", emergencySubtitle:"Perdita · Gas · Guasto auto · Emergenza animale",
  whatNeedsFixing:"Cosa deve essere riparato?",
  homeRepair:"Riparazioni casa", carProblems:"Problemi auto", techDevices:"Tech e dispositivi",
  garden:"Giardino", appliances:"Elettrodomestici", petHealth:"Salute animale",
  tapToFix:"Tocca per riparare →",
  enableLocBanner:"Attiva posizione per risultati vicini",
  enableLocDesc:"Trova officine, negozi e servizi di emergenza reali vicino a te",
  fixItNow:"Ripara ora 🔧", descOrPhoto:"Descrivi o fotografa il problema",
  takePhoto:"Scatta una foto o carica", photoDesc:"L'IA legge la foto e diagnostica il problema esatto",
  cameraUpload:"📷 Fotocamera / Carica", describeWords:"O descrivi a parole",
  getAIGuide:"🤖 Guida riparazione IA", commonProblems:"Problemi comuni",
  diagnosing:"Analisi del problema in corso…", diagnosingWait:"Circa 10 secondi…",
  aiUnavailable:"Analisi IA temporaneamente non disponibile",
  aiUnavailableDesc:"Il sistema IA è momentaneamente non disponibile. Riprovare.",
  aiNoKey:"Guida IA non configurata su questo deployment.",
  aiNoKeyDesc:"Aggiungi VITE_ANTHROPIC_KEY in Vercel → Impostazioni → Variabili d'ambiente e rideploya.",
  tryAgain:"Riprova",
  diagnosis:"🔍 Diagnosi", possibleCauses:"Cause possibili", safetyWarning:"⚠️ Avviso di sicurezza",
  stepByStep:"📋 Guida passo dopo passo", step:"Passo", of:"di",
  toolsNeeded:"🔩 Strumenti necessari", partsNeeded:"📦 Ricambi necessari", expertTip:"⭐ Consiglio esperto",
  proRequired:"👨‍🔧 Professionista richiesto", findProNearMe:"🗺️ Trova professionista vicino",
  findParts:"🔩 Trova ricambi", findPro:"👨‍🔧 Trova professionista", back:"Indietro", photoTip:"💡 Consiglio pro",
  emergencyMode:"Modalità emergenza", whatsHappening:"Cosa sta succedendo? 🚨",
  selectCategory:"Seleziona categoria per aiuto immediato",
  callNow:"📞 Chiama ora", tapToCall:"Tocca per chiamare",
  immediateSteps:"📋 Passi immediati", openMapNear:"Apre mappa vicino a te",
  emergencyPlumber:"Idraulico emergenza 24h",
  plumberQuery:"idraulico emergenza perdita acqua vicino a me",
  nearestGarage:"Officina più vicina", emergencyVet:"Veterinario emergenza",
  electricityProvider:"Fornitore elettricità", emergencyNumbers:"Numeri emergenza",
  animalClinicNear:"Clinica veterinaria vicino a me",
  findNearby:"🗺️ Vicino a te", refresh:"Aggiorna", loadingPlaces:"Caricamento luoghi…",
  noResults:"Nessun risultato trovato", noResultsDesc:"Prova un'altra categoria o apri Google Maps",
  openGoogleMaps:"🗺️ Apri in Google Maps", realResultsFrom:"risultati reali da OpenStreetMap",
  locationNeeded:"Posizione necessaria", locationNeededDesc:"Attiva GPS per trovare attività vicine",
  enableLocation:"Attiva posizione", couldNotLoad:"Impossibile caricare i luoghi",
  couldNotLoadDesc:"Verifica connessione e riprova",
  call:"Chiama", website:"Sito web", openNow:"Aperto ora",
  allResultsMap:"Tutti i risultati con recensioni e indicazioni",
  catGarage:"Officina", catParts:"Ricambi auto", catTyres:"Pneumatici",
  catPetrol:"Carburante", catHardware:"Ferramenta", catVet:"Veterinario", catIT:"Riparazione IT",
  partsFinder:"🔩 Cerca ricambi", partsSubtitle:"Trova ricambi esatti — negozi locali e online",
  searchingFor:"Per cosa cerchi ricambi?",
  catCar:"🚗 Auto", catHome:"🏠 Casa", catAppliance:"🍳 Elettrodomestico",
  catGarden:"🌿 Giardino", catTech:"💻 Tech", catBike:"🚲 Bici", catPets:"🐾 Animale",
  vehicleInputCar:"es. Fiat Punto 2019 o targa/modello",
  vehicleInputBike:"es. marca/modello bicicletta", vehicleInputHome:"es. numero modello elettrodomestico",
  vehicleInputDefault:"es. marca, modello o codice ricambio",
  vehicleHint:"🇩🇪 HSN/TSN · 🇬🇧 Targa · 🇺🇸 VIN · o modello",
  whatPartNeeded:"Quale ricambio ti serve?",
  partInputPlaceholder:"es. pastiglie freno, filtro aria, pompa acqua…",
  findPartsBtn:"🔍 Trova ricambi + migliori prezzi", typePartFirst:"Inserisci il nome del ricambio per cercare",
  localStores:"📍 Negozi locali", onlineStores:"🌍 Negozi online",
  findNearYou:"Trova vicino a te su Google Maps", gpsUsed:"Usa la tua posizione GPS",
  enableGPS:"Attiva GPS per risultati migliori", storesFor:"Negozi per", resultsFor:"Risultati per",
  vehicle:"veicolo", hsnDetected:"HSN/TSN Rilevato",
  hsnDesc:"Apre Autodoc per ricambi 100% compatibili con il tuo veicolo.",
};

T.pl = {
  detecting:"Wykrywanie języka…", langDetected:"Język wykryty!",
  continueIn:"Kontynuuj w", chooseOther:"Wybierz inny język", chooseLanguage:"Wybierz język",
  allowLocation:"Zezwól na lokalizację",
  locationDesc:"FixIt używa Twojej lokalizacji, aby znaleźć warsztaty, sklepy i służby ratunkowe w pobliżu.",
  allow:"Zezwól", skipNow:"Pomiń", gettingLoc:"Pobieranie lokalizacji…",
  locPrivacy:"Twoja lokalizacja jest używana tylko do znalezienia lokalnych usług. Nigdy nie jest przechowywana.",
  home:"Strona główna", fixNow:"Napraw", nearby:"W pobliżu", parts:"Części", emergency:"Nagły wypadek",
  goodMorning:"Dzień dobry,", goodAfternoon:"Dzień dobry,", goodEvening:"Dobry wieczór,",
  welcome:"Witaj w FixIt 👋", descProblem:"Opisz problem…",
  emergencyHelp:"⚡ Pomoc awaryjna", emergencySubtitle:"Wyciek · Gaz · Awaria auta · Nagły wypadek zwierzęcia",
  whatNeedsFixing:"Co wymaga naprawy?",
  homeRepair:"Naprawa domu", carProblems:"Problemy z autem", techDevices:"Technika i urządzenia",
  garden:"Ogród", appliances:"AGD", petHealth:"Zdrowie zwierzęcia",
  tapToFix:"Dotknij aby naprawić →",
  enableLocBanner:"Włącz lokalizację aby zobaczyć wyniki w pobliżu",
  enableLocDesc:"Znajdź prawdziwe warsztaty, sklepy i służby ratunkowe w pobliżu",
  fixItNow:"Napraw teraz 🔧", descOrPhoto:"Opisz lub sfotografuj problem",
  takePhoto:"Zrób zdjęcie lub prześlij", photoDesc:"AI odczytuje zdjęcie i diagnozuje dokładny problem",
  cameraUpload:"📷 Aparat / Prześlij", describeWords:"Lub opisz słowami",
  getAIGuide:"🤖 Pobierz poradnik naprawy AI", commonProblems:"Częste problemy",
  diagnosing:"Analiza problemu w toku…", diagnosingWait:"Około 10 sekund…",
  aiUnavailable:"Analiza AI chwilowo niedostępna",
  aiUnavailableDesc:"Nasz system AI jest tymczasowo niedostępny. Spróbuj ponownie.",
  aiNoKey:"Poradnik AI nie jest skonfigurowany w tym wdrożeniu.",
  aiNoKeyDesc:"Dodaj VITE_ANTHROPIC_KEY w Vercel → Ustawienia → Zmienne środowiskowe i wdróż ponownie.",
  tryAgain:"Spróbuj ponownie",
  diagnosis:"🔍 Diagnoza", possibleCauses:"Możliwe przyczyny", safetyWarning:"⚠️ Ostrzeżenie bezpieczeństwa",
  stepByStep:"📋 Instrukcja krok po kroku", step:"Krok", of:"z",
  toolsNeeded:"🔩 Potrzebne narzędzia", partsNeeded:"📦 Potrzebne części", expertTip:"⭐ Porada eksperta",
  proRequired:"👨‍🔧 Wymagany fachowiec", findProNearMe:"🗺️ Znajdź fachowca w pobliżu",
  findParts:"🔩 Znajdź części", findPro:"👨‍🔧 Znajdź fachowca", back:"Wstecz", photoTip:"💡 Porada pro",
  emergencyMode:"Tryb awaryjny", whatsHappening:"Co się dzieje? 🚨",
  selectCategory:"Wybierz kategorię aby uzyskać natychmiastową pomoc",
  callNow:"📞 Zadzwoń teraz", tapToCall:"Dotknij aby zadzwonić",
  immediateSteps:"📋 Natychmiastowe kroki", openMapNear:"Otwiera mapę w pobliżu",
  emergencyPlumber:"Awaryjny hydraulik 24h",
  plumberQuery:"awaryjny hydraulik wyciek wody w pobliżu",
  nearestGarage:"Najbliższy warsztat", emergencyVet:"Awaryjny weterynarz",
  electricityProvider:"Dostawca energii elektrycznej", emergencyNumbers:"Numery alarmowe",
  animalClinicNear:"Klinika weterynaryjna w pobliżu",
  findNearby:"🗺️ W pobliżu", refresh:"Odśwież", loadingPlaces:"Ładowanie miejsc…",
  noResults:"Nie znaleziono wyników", noResultsDesc:"Spróbuj innej kategorii lub otwórz Google Maps",
  openGoogleMaps:"🗺️ Otwórz w Google Maps", realResultsFrom:"prawdziwych wyników z OpenStreetMap",
  locationNeeded:"Lokalizacja wymagana", locationNeededDesc:"Włącz GPS aby znaleźć firmy w pobliżu",
  enableLocation:"Włącz lokalizację", couldNotLoad:"Nie można załadować miejsc",
  couldNotLoadDesc:"Sprawdź połączenie i spróbuj ponownie",
  call:"Zadzwoń", website:"Strona internetowa", openNow:"Otwarte teraz",
  allResultsMap:"Wszystkie wyniki z recenzjami i nawigacją",
  catGarage:"Warsztat", catParts:"Części samochodowe", catTyres:"Opony",
  catPetrol:"Stacja paliw", catHardware:"Sklep budowlany", catVet:"Weterynarz", catIT:"Naprawa IT",
  partsFinder:"🔩 Wyszukiwarka części", partsSubtitle:"Znajdź dokładne części — lokalne i online",
  searchingFor:"Czego szukasz części?",
  catCar:"🚗 Auto", catHome:"🏠 Dom", catAppliance:"🍳 AGD",
  catGarden:"🌿 Ogród", catTech:"💻 Technika", catBike:"🚲 Rower", catPets:"🐾 Zwierzę",
  vehicleInputCar:"np. VW Golf 2019 1.6 TDI lub numer rejestracyjny",
  vehicleInputBike:"np. marka/model roweru", vehicleInputHome:"np. numer modelu urządzenia",
  vehicleInputDefault:"np. marka, model lub numer części",
  vehicleHint:"🇩🇪 HSN/TSN · 🇬🇧 Rejestracja · 🇺🇸 VIN · lub model",
  whatPartNeeded:"Jakiej części potrzebujesz?",
  partInputPlaceholder:"np. klocki hamulcowe, filtr powietrza, pompa wody…",
  findPartsBtn:"🔍 Znajdź części + najlepsze ceny", typePartFirst:"Wpisz nazwę części aby wyszukać",
  localStores:"📍 Lokalne sklepy", onlineStores:"🌍 Sklepy online",
  findNearYou:"Znajdź w pobliżu na Google Maps", gpsUsed:"Używa Twojej lokalizacji GPS",
  enableGPS:"Włącz GPS dla lepszych wyników", storesFor:"Sklepy dla", resultsFor:"Wyniki dla",
  vehicle:"pojazd", hsnDetected:"HSN/TSN Wykryty",
  hsnDesc:"Otwiera Autodoc dla 100% kompatybilnych części z Twoim pojazdem.",
};

T.sr = {
  detecting:"Otkrivanje jezika…", langDetected:"Jezik otkriven!",
  continueIn:"Nastavi na", chooseOther:"Izaberi drugi jezik", chooseLanguage:"Izaberi jezik",
  allowLocation:"Dozvoli lokaciju",
  locationDesc:"FixIt koristi tvoju lokaciju da pronađe servisere, prodavnice delova i hitne službe u blizini.",
  allow:"Dozvoli", skipNow:"Preskoči", gettingLoc:"Detekcija lokacije…",
  locPrivacy:"Tvoja lokacija se koristi samo za nalaženje lokalnih servisa. Nikad se ne čuva.",
  home:"Početna", fixNow:"Popravi", nearby:"U blizini", parts:"Delovi", emergency:"Hitno",
  goodMorning:"Dobro jutro,", goodAfternoon:"Dobar dan,", goodEvening:"Dobro veče,",
  welcome:"Dobrodošao u FixIt 👋", descProblem:"Opiši problem…",
  emergencyHelp:"⚡ Hitna pomoć", emergencySubtitle:"Pukla cev · Gas · Kvar auta · Hitno sa ljubimcem",
  whatNeedsFixing:"Šta treba popraviti?",
  homeRepair:"Popravke u kući", carProblems:"Problemi sa autom", techDevices:"Tehnika i uređaji",
  garden:"Bašta", appliances:"Kućni aparati", petHealth:"Zdravlje ljubimaca",
  tapToFix:"Tapni za popravku →",
  enableLocBanner:"Aktiviraj lokaciju za rezultate u blizini",
  enableLocDesc:"Pronađi prave servisere, prodavnice i hitne službe u blizini",
  fixItNow:"Popravi odmah 🔧", descOrPhoto:"Opiši ili fotografiši problem",
  takePhoto:"Uslikaj ili učitaj fotografiju", photoDesc:"AI čita tvoju fotografiju i dijagnostikuje tačan problem",
  cameraUpload:"📷 Kamera / Učitaj", describeWords:"Ili opiši rečima",
  getAIGuide:"🤖 Dobij AI uputstvo za popravku", commonProblems:"Česti problemi",
  diagnosing:"Analiza problema u toku…", diagnosingWait:"Oko 10 sekundi…",
  aiUnavailable:"AI analiza trenutno nije dostupna",
  aiUnavailableDesc:"Naš AI sistem je privremeno nedostupan. Molimo pokušajte ponovo.",
  aiNoKey:"AI uputstvo nije konfigurisano u ovom deploymentu.",
  aiNoKeyDesc:"Dodaj VITE_ANTHROPIC_KEY u Vercel → Podešavanja → Promenljive okruženja i ponovo postavi.",
  tryAgain:"Pokušaj ponovo",
  diagnosis:"🔍 Dijagnoza", possibleCauses:"Mogući uzroci", safetyWarning:"⚠️ Upozorenje o bezbednosti",
  stepByStep:"📋 Korak po korak uputstvo", step:"Korak", of:"od",
  toolsNeeded:"🔩 Potreban alat", partsNeeded:"📦 Potrebni delovi", expertTip:"⭐ Stručni savet",
  proRequired:"👨‍🔧 Potreban stručnjak", findProNearMe:"🗺️ Pronađi stručnjaka u blizini",
  findParts:"🔩 Pronađi delove", findPro:"👨‍🔧 Pronađi stručnjaka", back:"Nazad", photoTip:"💡 Stručni savet",
  emergencyMode:"Hitni režim", whatsHappening:"Šta se dešava? 🚨",
  selectCategory:"Izaberi kategoriju za hitnu pomoć",
  callNow:"📞 Pozovi odmah", tapToCall:"Tapni za poziv",
  immediateSteps:"📋 Hitni koraci", openMapNear:"Otvara kartu u blizini",
  emergencyPlumber:"Hitni vodoinstalater 24h",
  plumberQuery:"hitni vodoinstalater popravka cevi u blizini",
  nearestGarage:"Najbliža garaža", emergencyVet:"Hitni veterinar odmah",
  electricityProvider:"Operator elektromreže", emergencyNumbers:"Hitni brojevi",
  animalClinicNear:"Veterinarska klinika u blizini",
  findNearby:"🗺️ U blizini", refresh:"Osveži", loadingPlaces:"Učitavanje mesta u blizini…",
  noResults:"Nisu pronađeni rezultati", noResultsDesc:"Pokušaj drugu kategoriju ili otvori Google Maps",
  openGoogleMaps:"🗺️ Otvori u Google Maps", realResultsFrom:"pravih rezultata od OpenStreetMap",
  locationNeeded:"Potrebna lokacija", locationNeededDesc:"Aktiviraj GPS za prave servisere u blizini",
  enableLocation:"Aktiviraj lokaciju", couldNotLoad:"Mesta nisu mogla da se učitaju",
  couldNotLoadDesc:"Proveri internet vezu i pokušaj ponovo",
  call:"Pozovi", website:"Veb sajt", openNow:"Otvoreno sada",
  allResultsMap:"Svi rezultati sa ocenama i navigacijom",
  catGarage:"Garaža", catParts:"Auto delovi", catTyres:"Gume",
  catPetrol:"Benzinska", catHardware:"Građevinski", catVet:"Veterinar", catIT:"IT servis",
  partsFinder:"🔩 Tražilica delova", partsSubtitle:"Pronađi tačne delove — pametna lokalna i online pretraga",
  searchingFor:"Za šta tražiš delove?",
  catCar:"🚗 Auto", catHome:"🏠 Dom", catAppliance:"🍳 Aparat",
  catGarden:"🌿 Bašta", catTech:"💻 Tehnika", catBike:"🚲 Bicikl", catPets:"🐾 Ljubimac",
  vehicleInputCar:"npr. VW Golf 2019 1.6 TDI ili registarski broj",
  vehicleInputBike:"npr. marka/model bicikla", vehicleInputHome:"npr. broj modela aparata",
  vehicleInputDefault:"npr. marka, model ili broj dela",
  vehicleHint:"🇩🇪 HSN/TSN · 🇬🇧 Registracija · 🇺🇸 VIN · ili model",
  whatPartNeeded:"Koji deo ti treba?",
  partInputPlaceholder:"npr. kočione obloge, vazdušni filter, vodena pumpa…",
  findPartsBtn:"🔍 Traži delove + beste cene", typePartFirst:"Unesi naziv dela za pretragu",
  localStores:"📍 Lokalne prodavnice", onlineStores:"🌍 Online prodavnice",
  findNearYou:"Pronađi u blizini na Google Maps", gpsUsed:"Koristi tvoju GPS lokaciju",
  enableGPS:"Aktiviraj GPS za bolje rezultate", storesFor:"Prodavnice za", resultsFor:"Rezultati za",
  vehicle:"vozilo", hsnDetected:"HSN/TSN Otkriven",
  hsnDesc:"Otvara Autodoc za 100% kompatibilne delove za tvoje vozilo.",
};

T.hr = {
  detecting:"Otkrivanje jezika…", langDetected:"Jezik otkriven!",
  continueIn:"Nastavi na", chooseOther:"Odaberi drugi jezik", chooseLanguage:"Odaberi jezik",
  allowLocation:"Dozvoli pristup lokaciji",
  locationDesc:"FixIt koristi tvoju lokaciju za pronalazak servisera, prodavaonica i hitnih službi u blizini.",
  allow:"Dozvoli lokaciju", skipNow:"Preskoči", gettingLoc:"Detekcija lokacije…",
  locPrivacy:"Tvoja lokacija koristi se samo za pronalazak lokalnih servisa. Nikad se ne pohranjuje.",
  home:"Početna", fixNow:"Popravi", nearby:"U blizini", parts:"Dijelovi", emergency:"Hitno",
  goodMorning:"Dobro jutro,", goodAfternoon:"Dobar dan,", goodEvening:"Dobra večer,",
  welcome:"Dobrodošao u FixIt 👋", descProblem:"Opiši problem…",
  emergencyHelp:"⚡ Hitna pomoć", emergencySubtitle:"Puknuta cijev · Plin · Kvar auta · Hitno za ljubimca",
  whatNeedsFixing:"Što treba popraviti?",
  homeRepair:"Popravci u kući", carProblems:"Problemi s autom", techDevices:"Tehnika i uređaji",
  garden:"Vrt", appliances:"Kućanski aparati", petHealth:"Zdravlje ljubimaca",
  tapToFix:"Tapni za popravku →",
  enableLocBanner:"Aktiviraj lokaciju za rezultate u blizini",
  enableLocDesc:"Pronađi prave servisere, prodavaonice i hitne službe u blizini",
  fixItNow:"Popravi odmah 🔧", descOrPhoto:"Opiši ili fotografiraj problem",
  takePhoto:"Uslikaj ili učitaj fotografiju", photoDesc:"AI čita tvoju fotografiju i dijagnosticira točan problem",
  cameraUpload:"📷 Kamera / Učitaj", describeWords:"Ili opiši riječima",
  getAIGuide:"🤖 Dobij AI upute za popravku", commonProblems:"Česti problemi",
  diagnosing:"Analiza problema u tijeku…", diagnosingWait:"Oko 10 sekundi…",
  aiUnavailable:"AI analiza trenutno nije dostupna",
  aiUnavailableDesc:"Naš AI sustav je privremeno nedostupan. Molimo pokušajte ponovo.",
  aiNoKey:"AI upute nisu konfigurirane na ovom deploymentu.",
  aiNoKeyDesc:"Dodaj VITE_ANTHROPIC_KEY u Vercel → Postavke → Varijable okoline i ponovo postavi.",
  tryAgain:"Pokušaj ponovo",
  diagnosis:"🔍 Dijagnoza", possibleCauses:"Mogući uzroci", safetyWarning:"⚠️ Upozorenje o sigurnosti",
  stepByStep:"📋 Korak po korak upute", step:"Korak", of:"od",
  toolsNeeded:"🔩 Potreban alat", partsNeeded:"📦 Potrebni dijelovi", expertTip:"⭐ Stručni savjet",
  proRequired:"👨‍🔧 Potreban stručnjak", findProNearMe:"🗺️ Pronađi stručnjaka u blizini",
  findParts:"🔩 Pronađi dijelove", findPro:"👨‍🔧 Pronađi stručnjaka", back:"Natrag", photoTip:"💡 Stručni savjet",
  emergencyMode:"Hitni način", whatsHappening:"Što se događa? 🚨",
  selectCategory:"Odaberi kategoriju za hitnu pomoć",
  callNow:"📞 Nazovi odmah", tapToCall:"Tapni za poziv",
  immediateSteps:"📋 Hitni koraci", openMapNear:"Otvara kartu u blizini",
  emergencyPlumber:"Hitni vodoinstalater 24h",
  plumberQuery:"hitni vodoinstalater popravak cijevi u blizini",
  nearestGarage:"Najbliža garaža", emergencyVet:"Hitni veterinar odmah",
  electricityProvider:"Operator elektromreže", emergencyNumbers:"Hitni brojevi",
  animalClinicNear:"Veterinarska klinika u blizini",
  findNearby:"🗺️ U blizini", refresh:"Osvježi", loadingPlaces:"Učitavanje mjesta u blizini…",
  noResults:"Nisu pronađeni rezultati", noResultsDesc:"Pokušaj drugu kategoriju ili otvori Google Maps",
  openGoogleMaps:"🗺️ Otvori u Google Maps", realResultsFrom:"pravih rezultata od OpenStreetMap",
  locationNeeded:"Potrebna lokacija", locationNeededDesc:"Aktiviraj GPS za prave servisere u blizini",
  enableLocation:"Aktiviraj lokaciju", couldNotLoad:"Mjesta se nisu mogla učitati",
  couldNotLoadDesc:"Provjeri internet vezu i pokušaj ponovo",
  call:"Nazovi", website:"Web stranica", openNow:"Otvoreno sada",
  allResultsMap:"Svi rezultati s ocjenama i navigacijom",
  catGarage:"Garaža", catParts:"Auto dijelovi", catTyres:"Gume",
  catPetrol:"Benzinska", catHardware:"Građevinski", catVet:"Veterinar", catIT:"IT servis",
  partsFinder:"🔩 Tražilica dijelova", partsSubtitle:"Pronađi točne dijelove — pametna lokalna i online pretraga",
  searchingFor:"Za što tražiš dijelove?",
  catCar:"🚗 Auto", catHome:"🏠 Dom", catAppliance:"🍳 Aparat",
  catGarden:"🌿 Vrt", catTech:"💻 Tehnika", catBike:"🚲 Bicikl", catPets:"🐾 Ljubimac",
  vehicleInputCar:"npr. VW Golf 2019 1.6 TDI ili registracija",
  vehicleInputBike:"npr. marka/model bicikla", vehicleInputHome:"npr. broj modela aparata",
  vehicleInputDefault:"npr. marka, model ili broj dijela",
  vehicleHint:"🇩🇪 HSN/TSN · 🇬🇧 Registracija · 🇺🇸 VIN · ili model",
  whatPartNeeded:"Koji dio ti treba?",
  partInputPlaceholder:"npr. kočione pločice, filter zraka, vodena pumpa…",
  findPartsBtn:"🔍 Traži dijelove + beste cijene", typePartFirst:"Unesi naziv dijela za pretragu",
  localStores:"📍 Lokalne prodavaonice", onlineStores:"🌍 Online prodavaonice",
  findNearYou:"Pronađi u blizini na Google Maps", gpsUsed:"Koristi tvoju GPS lokaciju",
  enableGPS:"Aktiviraj GPS za bolje rezultate", storesFor:"Prodavaonice za", resultsFor:"Rezultati za",
  vehicle:"vozilo", hsnDetected:"HSN/TSN Otkriven",
  hsnDesc:"Otvara Autodoc za 100% kompatibilne dijelove za tvoje vozilo.",
};

T.mk = {
  detecting:"Откривање јазик…", langDetected:"Јазикот е откриен!",
  continueIn:"Продолжи на", chooseOther:"Избери друг јазик", chooseLanguage:"Избери јазик",
  allowLocation:"Дозволи локација",
  locationDesc:"FixIt ја користи вашата локација за наоѓање сервисери, продавници и итни служби во близина.",
  allow:"Дозволи", skipNow:"Прескокни", gettingLoc:"Откривање локација…",
  locPrivacy:"Вашата локација се користи само за локални услуги. Никогаш не се зачувува.",
  home:"Почетна", fixNow:"Поправи", nearby:"Во близина", parts:"Делови", emergency:"Итно",
  goodMorning:"Добро утро,", goodAfternoon:"Добар ден,", goodEvening:"Добра вечер,",
  welcome:"Добредојдовте во FixIt 👋", descProblem:"Опишете го проблемот…",
  emergencyHelp:"⚡ Итна помош", emergencySubtitle:"Пукнат цевка · Гас · Дефект · Итно за миленик",
  whatNeedsFixing:"Што треба да се поправи?",
  homeRepair:"Поправки во дома", carProblems:"Проблеми со автомобилот", techDevices:"Техника и уреди",
  garden:"Градина", appliances:"Домашни апарати", petHealth:"Здравје на миленик",
  tapToFix:"Допри за поправка →",
  enableLocBanner:"Активирај локација за резултати во близина",
  enableLocDesc:"Најди вистински сервисери, продавници и итни служби во близина",
  fixItNow:"Поправи веднаш 🔧", descOrPhoto:"Опиши или фотографирај го проблемот",
  takePhoto:"Сними или прикачи фотографија", photoDesc:"АИ ја чита фотографијата и дијагностицира точно",
  cameraUpload:"📷 Камера / Прикачи", describeWords:"Или опиши со зборови",
  getAIGuide:"🤖 Добиј АИ упатство за поправка", commonProblems:"Чести проблеми",
  diagnosing:"Анализа на проблемот во тек…", diagnosingWait:"Околу 10 секунди…",
  aiUnavailable:"АИ анализата моментално не е достапна",
  aiUnavailableDesc:"Нашиот АИ систем е привремено недостапен. Обидете се повторно.",
  aiNoKey:"АИ упатството не е конфигурирано на ова распоредување.",
  aiNoKeyDesc:"Додади VITE_ANTHROPIC_KEY во Vercel → Поставки → Променливи на средина и повторно постави.",
  tryAgain:"Обиди се повторно",
  diagnosis:"🔍 Дијагноза", possibleCauses:"Можни причини", safetyWarning:"⚠️ Предупредување за безбедност",
  stepByStep:"📋 Чекор по чекор упатство", step:"Чекор", of:"од",
  toolsNeeded:"🔩 Потребни алати", partsNeeded:"📦 Потребни делови", expertTip:"⭐ Стручен совет",
  proRequired:"👨‍🔧 Потребен стручњак", findProNearMe:"🗺️ Најди стручњак во близина",
  findParts:"🔩 Најди делови", findPro:"👨‍🔧 Најди стручњак", back:"Назад", photoTip:"💡 Стручен совет",
  emergencyMode:"Итен режим", whatsHappening:"Што се случува? 🚨",
  selectCategory:"Избери категорија за итна помош",
  callNow:"📞 Јави веднаш", tapToCall:"Допри за повик",
  immediateSteps:"📋 Итни чекори", openMapNear:"Отвора карта во близина",
  emergencyPlumber:"Итен водоинсталатер 24ч",
  plumberQuery:"итен водоинсталатер поправка цевки во близина",
  nearestGarage:"Најблиска гаража", emergencyVet:"Итен ветеринар веднаш",
  electricityProvider:"Оператор на електромрежа", emergencyNumbers:"Итни броеви",
  animalClinicNear:"Ветеринарска клиника во близина",
  findNearby:"🗺️ Во близина", refresh:"Освежи", loadingPlaces:"Вчитување места…",
  noResults:"Нема резултати во близина", noResultsDesc:"Пробај друга категорија или отвори Google Maps",
  openGoogleMaps:"🗺️ Отвори во Google Maps", realResultsFrom:"вистински резултати од OpenStreetMap",
  locationNeeded:"Потребна локација", locationNeededDesc:"Активирај GPS за вистински сервисери во близина",
  enableLocation:"Активирај локација", couldNotLoad:"Местата не можеа да се вчитаат",
  couldNotLoadDesc:"Провери интернет врска и обиди се повторно",
  call:"Јави", website:"Веб страница", openNow:"Отворено сега",
  allResultsMap:"Сите резултати со оцени и навигација",
  catGarage:"Гаража", catParts:"Авто делови", catTyres:"Гуми",
  catPetrol:"Бензинска", catHardware:"Градежен", catVet:"Ветеринар", catIT:"ИТ сервис",
  partsFinder:"🔩 Тражилица делови", partsSubtitle:"Најди точни делови — локални и онлајн продавници",
  searchingFor:"За што бараш делови?",
  catCar:"🚗 Автомобил", catHome:"🏠 Дом", catAppliance:"🍳 Апарат",
  catGarden:"🌿 Градина", catTech:"💻 Техника", catBike:"🚲 Велосипед", catPets:"🐾 Миленик",
  vehicleInputCar:"пр. VW Golf 2019 или регистарски број",
  vehicleInputBike:"пр. марка/модел велосипед", vehicleInputHome:"пр. број на модел на апаратот",
  vehicleInputDefault:"пр. марка, модел или број на дел",
  vehicleHint:"🇩🇪 HSN/TSN · 🇬🇧 Регистрација · 🇺🇸 VIN · или модел",
  whatPartNeeded:"Кој дел ти треба?",
  partInputPlaceholder:"пр. сопирачки облоги, воздушен филтер, водна пумпа…",
  findPartsBtn:"🔍 Барај делови + најдобри цени", typePartFirst:"Внеси назив на дел за пребарување",
  localStores:"📍 Локални продавници", onlineStores:"🌍 Онлајн продавници",
  findNearYou:"Најди во близина на Google Maps", gpsUsed:"Ја користи твојата GPS локација",
  enableGPS:"Активирај GPS за подобри резултати", storesFor:"Продавници за", resultsFor:"Резултати за",
  vehicle:"возило", hsnDetected:"HSN/TSN Откриен",
  hsnDesc:"Отвора Autodoc за 100% компатибилни делови за твоето возило.",
};

T.tr = {
  detecting:"Dil algılanıyor…", langDetected:"Dil algılandı!",
  continueIn:"Devam et", chooseOther:"Başka dil seç", chooseLanguage:"Dil seç",
  allowLocation:"Konuma izin ver",
  locationDesc:"FixIt, yakınızdaki tamirciler, yedek parça ve acil hizmetleri bulmak için konumunuzu kullanır.",
  allow:"İzin ver", skipNow:"Atla", gettingLoc:"Konum alınıyor…",
  locPrivacy:"Konumunuz yalnızca yerel hizmetleri bulmak için kullanılır. Asla saklanmaz.",
  home:"Ana Sayfa", fixNow:"Tamir Et", nearby:"Yakın", parts:"Parçalar", emergency:"Acil",
  goodMorning:"Günaydın,", goodAfternoon:"İyi günler,", goodEvening:"İyi akşamlar,",
  welcome:"FixIt'e Hoş Geldiniz 👋", descProblem:"Problemi tanımlayın…",
  emergencyHelp:"⚡ Acil Yardım", emergencySubtitle:"Su borusu · Gaz · Araba arızası · Evcil hayvan acil",
  whatNeedsFixing:"Ne tamir edilmeli?",
  homeRepair:"Ev tamiri", carProblems:"Araba sorunları", techDevices:"Teknoloji ve cihazlar",
  garden:"Bahçe", appliances:"Ev aletleri", petHealth:"Evcil hayvan sağlığı",
  tapToFix:"Tamir etmek için dokun →",
  enableLocBanner:"Yakın sonuçlar için konumu etkinleştir",
  enableLocDesc:"Yakınızdaki gerçek tamircileri, mağazaları ve acil servisleri bulun",
  fixItNow:"Şimdi tamir et 🔧", descOrPhoto:"Problemi tanımlayın veya fotoğraflayın",
  takePhoto:"Fotoğraf çek veya yükle", photoDesc:"Yapay zeka fotoğrafınızı okur ve tam problemi teşhis eder",
  cameraUpload:"📷 Kamera / Yükle", describeWords:"Veya kelimelerle tanımlayın",
  getAIGuide:"🤖 Yapay zeka tamir kılavuzu al", commonProblems:"Sık problemler",
  diagnosing:"Problem analiz ediliyor…", diagnosingWait:"Yaklaşık 10 saniye…",
  aiUnavailable:"Yapay zeka analizi geçici olarak kullanılamıyor",
  aiUnavailableDesc:"Yapay zeka sistemimiz geçici olarak kullanılamıyor. Lütfen tekrar deneyin.",
  aiNoKey:"Yapay zeka kılavuzu bu dağıtımda yapılandırılmamış.",
  aiNoKeyDesc:"Vercel → Ayarlar → Ortam Değişkenleri'ne VITE_ANTHROPIC_KEY ekleyin ve yeniden dağıtın.",
  tryAgain:"Tekrar dene",
  diagnosis:"🔍 Teşhis", possibleCauses:"Olası nedenler", safetyWarning:"⚠️ Güvenlik uyarısı",
  stepByStep:"📋 Adım adım kılavuz", step:"Adım", of:"den",
  toolsNeeded:"🔩 Gerekli araçlar", partsNeeded:"📦 Gerekli parçalar", expertTip:"⭐ Uzman ipucu",
  proRequired:"👨‍🔧 Profesyonel gerekli", findProNearMe:"🗺️ Yakınımda profesyonel bul",
  findParts:"🔩 Parça bul", findPro:"👨‍🔧 Profesyonel bul", back:"Geri", photoTip:"💡 Pro ipucu",
  emergencyMode:"Acil mod", whatsHappening:"Ne oluyor? 🚨",
  selectCategory:"Anında yardım için kategori seçin",
  callNow:"📞 Şimdi ara", tapToCall:"Aramak için dokun",
  immediateSteps:"📋 Acil adımlar", openMapNear:"Konumunuz yakınında harita açar",
  emergencyPlumber:"Acil tesisatçı 24s",
  plumberQuery:"acil tesisatçı su kaçağı yakınımda",
  nearestGarage:"En yakın garaj", emergencyVet:"Acil veteriner",
  electricityProvider:"Elektrik şirketi", emergencyNumbers:"Acil numaralar",
  animalClinicNear:"Yakınımda veteriner klinik",
  findNearby:"🗺️ Yakın", refresh:"Yenile", loadingPlaces:"Yerler yükleniyor…",
  noResults:"Yakında sonuç bulunamadı", noResultsDesc:"Başka bir kategori deneyin veya Google Maps'i açın",
  openGoogleMaps:"🗺️ Google Maps'te aç", realResultsFrom:"gerçek sonuç OpenStreetMap'tan",
  locationNeeded:"Konum gerekli", locationNeededDesc:"Yakındaki işletmeleri bulmak için GPS'i etkinleştirin",
  enableLocation:"Konumu etkinleştir", couldNotLoad:"Yerler yüklenemedi",
  couldNotLoadDesc:"İnternet bağlantınızı kontrol edin ve tekrar deneyin",
  call:"Ara", website:"Web sitesi", openNow:"Şu an açık",
  allResultsMap:"İncelemeler ve yol tarifiyle tüm sonuçlar",
  catGarage:"Garaj", catParts:"Araba parçaları", catTyres:"Lastikler",
  catPetrol:"Benzin", catHardware:"Nalburiye", catVet:"Veteriner", catIT:"BT tamiri",
  partsFinder:"🔩 Parça bulucu", partsSubtitle:"Tam parçaları bulun — yerel ve çevrimiçi",
  searchingFor:"Ne için parça arıyorsunuz?",
  catCar:"🚗 Araba", catHome:"🏠 Ev", catAppliance:"🍳 Alet",
  catGarden:"🌿 Bahçe", catTech:"💻 Teknoloji", catBike:"🚲 Bisiklet", catPets:"🐾 Evcil hayvan",
  vehicleInputCar:"örn. Toyota Corolla 2019 veya model",
  vehicleInputBike:"örn. bisiklet markası/modeli", vehicleInputHome:"örn. aletin model numarası",
  vehicleInputDefault:"örn. marka, model veya parça numarası",
  vehicleHint:"🇩🇪 HSN/TSN · 🇬🇧 Plaka · 🇺🇸 VIN · veya model",
  whatPartNeeded:"Hangi parçaya ihtiyacınız var?",
  partInputPlaceholder:"örn. fren balataları, hava filtresi, su pompası…",
  findPartsBtn:"🔍 Parça + en iyi fiyatları bul", typePartFirst:"Aramak için parça adı girin",
  localStores:"📍 Yerel mağazalar", onlineStores:"🌍 Çevrimiçi mağazalar",
  findNearYou:"Google Maps'te yakınımda bul", gpsUsed:"GPS konumunuzu kullanıyor",
  enableGPS:"Daha iyi sonuçlar için GPS'i etkinleştirin", storesFor:"Mağazalar", resultsFor:"Sonuçlar",
  vehicle:"araç", hsnDetected:"HSN/TSN Algılandı",
  hsnDesc:"Aracınız için %100 uyumlu parçalar için Autodoc açar.",
};

// ─── VERIFY ALL LANGUAGES HAVE ALL KEYS ──────────────────────────────────────
export function verifyTranslations() {
  const results = {};
  for (const lc of Object.keys(LANGS)) {
    const obj = T[lc] || {};
    const missing = KEYS.filter(k => !(k in obj));
    results[lc] = missing;
  }
  return results;
}

export const tx = (lang, key) => {
  const obj = T[lang] || T.en;
  return obj[key] ?? T.en[key] ?? key;
};
