-- ============================================================
-- FixIt — Production Supabase Schema
-- Generated by auditing: src/auth.js, src/useAuth.js,
--   src/App.jsx, api/checkout.js, api/webhook.js
--
-- Table names match the code exactly:
--   profiles  — auth.js getProfile(), webhook.js upsert
--   usage     — auth.js checkUsage() / incrementUsage()
--   payments  — webhook.js insert
--
-- Safe to run on a fresh Supabase project.
-- Idempotent: uses CREATE ... IF NOT EXISTS and OR REPLACE.
-- ============================================================


-- ════════════════════════════════════════════════════════════
-- SHARED: updated_at trigger
-- ════════════════════════════════════════════════════════════

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Revoke default public execute; grant only to service_role and authenticated
revoke execute on function public.set_updated_at() from public, anon;
grant  execute on function public.set_updated_at() to service_role, authenticated;


-- ════════════════════════════════════════════════════════════
-- 1. PROFILES
-- Columns written by the code:
--   webhook.js  → id, is_pro, plan, stripe_customer_id, updated_at
--   auth.js     → id, email, is_pro (read via select *)
--   App.jsx     → authProfile?.plan  (read)
--   useAuth.js  → profile?.is_pro    (read)
-- ════════════════════════════════════════════════════════════

create table if not exists public.profiles (
  id                 uuid        primary key references auth.users(id) on delete cascade,
  email              text        not null default '',
  is_pro             boolean     not null default false,
  plan               text,                          -- 'monthly' | 'yearly' | null
  stripe_customer_id text,                          -- written by webhook only
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

-- Index used by webhook: .update(...).eq('stripe_customer_id', customerId)
create index if not exists profiles_stripe_customer_idx
  on public.profiles(stripe_customer_id)
  where stripe_customer_id is not null;

-- updated_at trigger
drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- ── RLS ───────────────────────────────────────────────────────────────────────
alter table public.profiles enable row level security;

-- User may read their own row (auth.js getProfile uses select *)
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select
  using (auth.uid() = id);

-- No user-level UPDATE policy — all writes go through:
--   • handle_new_user trigger (signup)
--   • webhook (service_role, bypasses RLS)
-- This prevents a user from setting is_pro/plan/stripe_customer_id via the client.

-- ── Least-privilege grants ────────────────────────────────────────────────────
-- anon: no access (not needed before login)
-- authenticated: select own row only (enforced by RLS above)
grant select on public.profiles to authenticated;
-- service_role already has full access; no explicit grant needed


-- ════════════════════════════════════════════════════════════
-- 2. USAGE
-- Exact column names from auth.js checkUsage() / incrementUsage():
--   user_id, diagnosis_count, free_limit, updated_at
--
-- Free model (from auth.js):
--   free_limit = 1 (one free diagnosis)
--   Pro users bypass this check entirely (is_pro checked first)
--   No daily/monthly reset — intentionally a total usage counter (persists for account lifetime)
-- ════════════════════════════════════════════════════════════

create table if not exists public.usage (
  user_id         uuid        primary key references auth.users(id) on delete cascade,
  diagnosis_count int         not null default 0,
  free_limit      int         not null default 1,   -- always 1 per business logic
  updated_at      timestamptz not null default now()
);

drop trigger if exists usage_set_updated_at on public.usage;
create trigger usage_set_updated_at
  before update on public.usage
  for each row execute function public.set_updated_at();

-- ── RLS ───────────────────────────────────────────────────────────────────────
alter table public.usage enable row level security;

-- User may read their own row (auth.js checkUsage reads select *)
drop policy if exists "usage_select_own" on public.usage;
create policy "usage_select_own"
  on public.usage for select
  using (auth.uid() = user_id);

-- No direct UPDATE/INSERT policy for authenticated users.
-- All writes go through:
--   • handle_new_user trigger (creates the row)
--   • consume_free_diagnosis() RPC (increments safely, server-side)
-- This prevents a client from resetting diagnosis_count to 0.

grant select on public.usage to authenticated;


-- ════════════════════════════════════════════════════════════
-- 3. PAYMENTS
-- Exact columns from webhook.js insert:
--   user_id, stripe_customer_id, stripe_session_id, plan, status, created_at
-- ════════════════════════════════════════════════════════════

create table if not exists public.payments (
  id                 uuid        primary key default gen_random_uuid(),
  user_id            uuid        references auth.users(id) on delete set null,
  stripe_customer_id text,
  stripe_session_id  text        unique,             -- prevents duplicate webhook inserts
  plan               text,                           -- 'monthly' | 'yearly'
  status             text,                           -- 'completed'
  created_at         timestamptz not null default now()
);

create index if not exists payments_user_id_idx on public.payments(user_id);
create index if not exists payments_stripe_customer_idx
  on public.payments(stripe_customer_id)
  where stripe_customer_id is not null;

-- ── RLS ───────────────────────────────────────────────────────────────────────
alter table public.payments enable row level security;

-- User may read their own payment history (read-only)
drop policy if exists "payments_select_own" on public.payments;
create policy "payments_select_own"
  on public.payments for select
  using (auth.uid() = user_id);

-- No insert/update/delete for authenticated users.
-- webhook.js uses service_role key which bypasses RLS.

grant select on public.payments to authenticated;


-- ════════════════════════════════════════════════════════════
-- 4. AUTO-PROVISION ON SIGNUP
-- Creates profile + usage rows when auth.users is inserted.
-- Matches the belt-and-suspenders upsert in auth.js signUp().
-- ════════════════════════════════════════════════════════════

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Create profile row; safe if trigger fires after an existing upsert from auth.js
  insert into public.profiles (id, email, is_pro, created_at, updated_at)
  values (
    new.id,
    coalesce(new.email, ''),
    false,
    now(),
    now()
  )
  on conflict (id) do nothing;

  -- Create usage row with free_limit=1 matching auth.js business logic
  insert into public.usage (user_id, diagnosis_count, free_limit, updated_at)
  values (new.id, 0, 1, now())
  on conflict (user_id) do nothing;

  return new;
end;
$$;

revoke execute on function public.handle_new_user() from public, anon, authenticated;
grant  execute on function public.handle_new_user() to service_role;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- ════════════════════════════════════════════════════════════
-- 5. SECURE DIAGNOSIS INCREMENT RPC
-- Replaces the direct usage upsert in auth.js incrementUsage().
--
-- Security properties:
--   • Only increments — cannot decrease or reset count
--   • Re-checks is_pro server-side (cannot be spoofed by client)
--   • Returns {allowed, diagnosis_count, is_pro} matching auth.js callers
--   • Atomic: read + write in one transaction, no TOCTOU race
--   • Revoked from anon; granted only to authenticated
-- ════════════════════════════════════════════════════════════

create or replace function public.consume_free_diagnosis(p_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_is_pro       boolean;
  v_count        int;
  v_limit        int;
begin
  -- Validate caller: only the authenticated user may call this for themselves
  if auth.uid() is null or auth.uid() <> p_user_id then
    raise exception 'Unauthorized';
  end if;

  -- Check Pro status server-side (never trust client-supplied value)
  select is_pro into v_is_pro from public.profiles where id = p_user_id;
  if v_is_pro then
    return jsonb_build_object('allowed', true, 'is_pro', true, 'diagnosis_count', null);
  end if;

  -- Read current usage with FOR UPDATE to prevent concurrent double-spend
  select diagnosis_count, free_limit
    into v_count, v_limit
    from public.usage
   where user_id = p_user_id
     for update;

  if not found then
    raise exception 'Usage row not found for user %', p_user_id;
  end if;

  -- Already at or over limit
  if v_count >= v_limit then
    return jsonb_build_object('allowed', false, 'is_pro', false, 'diagnosis_count', v_count);
  end if;

  -- Atomic increment
  update public.usage
     set diagnosis_count = v_count + 1,
         updated_at      = now()
   where user_id = p_user_id;

  return jsonb_build_object('allowed', true, 'is_pro', false, 'diagnosis_count', v_count + 1);
end;
$$;

-- Only authenticated users (logged-in) may call this
revoke execute on function public.consume_free_diagnosis(uuid) from public, anon;
grant  execute on function public.consume_free_diagnosis(uuid) to authenticated;


-- ════════════════════════════════════════════════════════════
-- 6. COLUMN-LEVEL SECURITY NOTES
-- Supabase/PostgREST enforces RLS row-level access, but column-
-- level grants are the correct tool to restrict specific fields.
-- Since we give no UPDATE policy to authenticated users on profiles,
-- the dangerous columns (is_pro, plan, stripe_customer_id) are
-- already fully protected — no column grants needed.
-- ════════════════════════════════════════════════════════════


-- ════════════════════════════════════════════════════════════
-- VERIFICATION QUERIES (run after setup to confirm)
-- ════════════════════════════════════════════════════════════

-- 1. Confirm tables exist with correct columns:
-- select column_name, data_type, is_nullable, column_default
--   from information_schema.columns
--  where table_schema = 'public'
--    and table_name in ('profiles','usage','payments')
--  order by table_name, ordinal_position;

-- 2. Confirm RLS is enabled:
-- select tablename, rowsecurity
--   from pg_tables
--  where schemaname = 'public';

-- 3. Confirm trigger fires on signup:
-- select trigger_name, event_manipulation, event_object_table
--   from information_schema.triggers
--  where trigger_schema = 'public' or event_object_schema = 'extensions';

-- 4. Manually grant Pro (testing only):
-- update public.profiles
--    set is_pro = true, plan = 'yearly', updated_at = now()
--  where email = 'you@example.com';

-- 5. Check a user's full state:
-- select p.id, p.email, p.is_pro, p.plan, p.stripe_customer_id,
--        u.diagnosis_count, u.free_limit
--   from public.profiles p
--   join public.usage u on u.user_id = p.id
--  where p.email = 'you@example.com';


-- ── admin_consume_diagnosis — service-role variant ──────────────────────────
-- Called by api/diagnose.js (server-side, service-role key) AFTER a successful
-- AI response to atomically increment the free usage counter.
-- No auth.uid() check — authentication was already done via JWT verification
-- in the API handler before this function is called.
-- Uses FOR UPDATE to prevent concurrent double-spend.
CREATE OR REPLACE FUNCTION public.admin_consume_diagnosis(p_user_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_is_pro boolean;
  v_count  int;
  v_limit  int;
BEGIN
  -- Check Pro status — if Pro, nothing to consume
  SELECT is_pro INTO v_is_pro FROM public.profiles WHERE id = p_user_id;
  IF v_is_pro THEN
    RETURN jsonb_build_object('consumed', false, 'is_pro', true);
  END IF;

  -- Atomic read-with-lock + increment
  SELECT diagnosis_count, free_limit
    INTO v_count, v_limit
    FROM public.usage
   WHERE user_id = p_user_id
     FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Usage row not found for user %', p_user_id;
  END IF;

  -- Already at limit — guard against race between check and commit
  IF v_count >= v_limit THEN
    RETURN jsonb_build_object('consumed', false, 'is_pro', false,
                              'already_at_limit', true, 'count', v_count);
  END IF;

  UPDATE public.usage
     SET diagnosis_count = v_count + 1,
         updated_at      = now()
   WHERE user_id = p_user_id;

  RETURN jsonb_build_object('consumed', true, 'is_pro', false, 'new_count', v_count + 1);
END;
$$;

-- Restrict execution to service_role only (anon/authenticated may not call this)
REVOKE EXECUTE ON FUNCTION public.admin_consume_diagnosis(uuid) FROM PUBLIC, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.admin_consume_diagnosis(uuid) TO service_role;
